### PR TITLE
SP23_Sprint2

### PR DESCRIPTION
**Pull request by simranmakandar98**
Planned test scripts + Following code changes:

#2231 - Create project, save draft
#2232 - Project search, apply filter
#2368 - Display Focus Area, Community Partner, Campus Partner, Drafts should display only in 'My Drafts'
#2371 - default 0 in projects\models.py

### CODE REVIEW

**Review by SachinPawaskarUNO — CHANGES_REQUESTED** [review]
@simranmakandar98 Issues that needed to be resolved.

1. Why  is package-lock.json file in .gitgnore?
2. Issues with cypress scripts, Please use best practices for DOM selectors such as data-cy or data-test
3. Sensitive information should not be in files being pushed to GitHub

Please remind me to discuss this with team.

**Comment by simranmakandar98** [comment]
Team comment for question 2: 
_For 2 - We already started these, and will continue implementing in the test scripts. Files in archives have problems like this and be sure we will be deleting this in further sprints_

**Review by SachinPawaskarUNO — APPROVED** [review]
Looks good.

**Comment by SachinPawaskarUNO** [comment]
@simranmakandar98 Please remind me to discuss this pull request with the team when we meet next.

**Comment by simranmakandar98** [comment]
Will do, Dr. Pawaskar. 
@SachinPawaskarUNO 

Thank you so much for your feedback on commits.

**Pull request merged**
